trigger:
- main

pool:
  vmImage: ubuntu-latest

stages:
- stage: Build
  jobs:
  - job: Build
    steps:
      - task: Npm@1
        inputs:
          command: 'install'
          workingDir: './'
      - task: Npm@1
        inputs:
          command: 'custom'
          workingDir: './'
          customCommand: 'run build'
      - task: PublishBuildArtifacts@1
        inputs:
          PathtoPublish: 'build'
          ArtifactName: 'drop'
          publishLocation: 'Container'
- stage: Deploy
  jobs:
  - job: Deploy
    steps:
      - task: DownloadBuildArtifacts@1
        inputs:
          buildType: 'current'
          downloadType: 'single'
          artifactName: 'drop'
          downloadPath: '$(System.ArtifactsDirectory)/build'
      - task: AzureRmWebAppDeployment@4
        inputs:
          ConnectionType: 'AzureRM'
          azureSubscription: 'Pay-As-You-Go (c0ba8b80-3f63-46bf-9763-7df38cae14c8)'
          appType: 'webAppLinux'
          WebAppName: 'youtube-app-clone'
          packageForLinux: '$(System.ArtifactsDirectory)/build'
          RuntimeStack: 'STATICSITE|1.0'

